spring.application.name=Walletwise
# 🌐 Spring Boot Cloud Database Routing Matrix
spring.datasource.url=jdbc:mysql://mysql-d2983c3-rrajasekar101206-94f0.d.aivencloud.com:18135/defaultdb?useSSL=true&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin

# 🔑 Paste your secret password string inside the quotes below!
spring.datasource.password=${DB_PASSWORD}

# 🏗️ Automated Schema Mapping Constraints
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true